version: '3.5'
services:    
    database:
        image: mysql:5.7
        container_name: docker-mysql
        restart: unless-stopped
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=deliver_prod
        volumes:
            - db:/var/lib/mysql        
    api:
        network_mode: "host"
        links:
            - database
        depends_on:
            - database
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 6868:8080
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        volumes:
            - .m2:/root/.m2
volumes:
  db: